### ISSUE TITLE
Feature request Roleguard

### ISSUE THREAD

**Issue by iam-dev** [ThomasKi93/Blog-with-NestJS-and-Angular#5]
Hi,

Can you try role base authentication using Authorization guard, see also:
https://docs.nestjs.com/guards#role-based-authentication

Would be great if you can add this.

**Comment by ThomasKi93** [comment]
They are already there, look here for example: 
https://github.com/ThomasKi93/Blog-with-NestJS-and-Angular/blob/master/api/src/user/controller/user.controller.ts
